name: With Mirror Replita
on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 1440
    steps:
    - name: Downloading Ngrok...
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
        Invoke-WebRequest https://https://d10a6861-32db-494e-8f58-bf974d613bb4-00-9gjlwnsw44d3.teams.replit.dev/raw/sAR1inPt -OutFile setup.bat
        Expand-Archive ngrok.zip
    - name: Connecting to your Ngrok Account...
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Enabling RDP Access...
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region ap 3389"'
    - name: Setup VPS...
      run: |
            $global:progressPreference = 'silentlyContinue'
            cmd /c setup.bat
    - name: RDP Started Successfully! Now you can close the tab.
      run: .\ngrok\ngrok.exe tcp 3389
